# -*- coding: utf-8 -*-
"""Mini_PdfDataExtraction_PyMuPdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MH3-e1rl_9GgfubcYkUR5NIVAGIgcyT
"""

!pip install PyMuPDF

import re
import json
from datetime import datetime

import pymupdf


def build_positioned_text(page):
    words = page.get_text("words")
    joined_parts, spans, cursor = [], [], 0
    for x0, y0, x1, y1, text, *_ in words:
        joined_parts.append(text)
        start, end = cursor, cursor + len(text)
        spans.append((start, end, (x0, y0, x1, y1)))
        cursor = end + 1
    return " ".join(joined_parts), spans


def bbox_for_match(match, spans):
    m_start, m_end = match.start(), match.end()
    boxes = [bbox for (s, e, bbox) in spans if s < m_end and e > m_start]
    if not boxes:
        return None
    x0 = min(b[0] for b in boxes); y0 = min(b[1] for b in boxes)
    x1 = max(b[2] for b in boxes); y1 = max(b[3] for b in boxes)
    return (round(x0, 1), round(y0, 1), round(x1, 1), round(y1, 1))


def find_first_with_bbox(page, pattern):
    text, spans = build_positioned_text(page)
    m = pattern.search(text)
    if not m:
        return None
    value = m.group(1) if m.groups() else m.group(0)
    return {"text": m.group(0).strip(), "value": value.strip(), "bbox": bbox_for_match(m, spans)}


def is_real_date(text: str) -> bool:
    for fmt in ["%Y%m%d", "%Y-%m-%d", "%m/%d/%Y", "%d %B %Y", "%d %B, %Y"]:
        try:
            datetime.strptime(text.strip(), fmt)
            return True
        except ValueError:
            continue
    return False


def to_iso(yyyymmdd: str) -> str:
    return datetime.strptime(yyyymmdd, "%Y%m%d").strftime("%Y-%m-%d")


FIELD_PATTERNS = {
    "vendor_name":        re.compile(r"\b(Cytiva)\b"),
    "document_type":      re.compile(r"\b(Certificate of Quality)\b"),
    "manufacturing_date": re.compile(r"Date of Manufacture:?\s*(\d{8})"),
    "expiration_date":    re.compile(r"Expiration Date:?\s*(\d{8})"),
    "revision_number":    re.compile(r"\b(\d{8}\s+Rev\s+[A-Z]{1,3})\b"),
    "lot_number":         re.compile(r"Lot Number:?\s*\n?\s*(\S+)"),
}


def extract_all_fields(pdf_path: str) -> list[dict]:
    doc = pymupdf.open(pdf_path)
    results = []
    for page_num, page in enumerate(doc, start=1):
        page_fields = {}
        for field_name, pattern in FIELD_PATTERNS.items():
            match = find_first_with_bbox(page, pattern)
            if not match:
                continue
            if field_name in ("manufacturing_date", "expiration_date"):
                if not is_real_date(match["value"]):
                    continue
                match["value"] = to_iso(match["value"])
            page_fields[field_name] = match
        if page_fields:
            results.append({"page": page_num, "fields": page_fields})
    doc.close()
    return results


def extract_table(pdf_path: str, page_num: int) -> dict | None:
    doc = pymupdf.open(pdf_path)
    page = doc[page_num - 1]
    tabs = page.find_tables()
    if not tabs.tables:
        return None
    t = tabs.tables[0]
    return {"page": page_num, "bbox": [round(v, 1) for v in t.bbox], "rows": t.extract()}


def draw_field_boxes(pdf_path: str, page_num: int, fields: dict, zoom: float = 2.0, out_path: str = "field_boxes.png"):
    import cv2
    import numpy as np

    doc = pymupdf.open(pdf_path)
    page = doc[page_num - 1]
    mat = pymupdf.Matrix(zoom, zoom)
    pix = page.get_pixmap(matrix=mat)
    img = np.frombuffer(pix.samples, dtype=np.uint8).reshape(pix.height, pix.width, pix.n)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    for name, m in fields.items():
        if not m["bbox"]:
            continue
        x0, y0, x1, y1 = [int(v * zoom) for v in m["bbox"]]
        cv2.rectangle(img, (x0, y0), (x1, y1), (0, 0, 255), 2)
        cv2.putText(img, name, (x0, max(y0 - 6, 10)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)

    cv2.imwrite(out_path, img)
    return out_path


if __name__ == "__main__":
    pdf_path = "sample-sdf-document.pdf"

    field_results = extract_all_fields(pdf_path)
    for page_result in field_results:
        print(f"--- Page {page_result['page']} ---")
        for name, m in page_result["fields"].items():
            print(f"  {name:20s}: '{m['value']}'   bbox={m['bbox']}")

    flat_output = []
    for page_result in field_results:
        for name, m in page_result["fields"].items():
            flat_output.append({
                "page": page_result["page"],
                "field": name,
                "text": m["text"],
                "value": m["value"],
                "bbox": list(m["bbox"]),
            })
    print(json.dumps(flat_output, indent=2))

    table = extract_table(pdf_path, 3)
    if table:
        print(f"bbox: {table['bbox']}")
        for row in table["rows"]:
            print(row)

    page_2_fields = next((p["fields"] for p in field_results if p["page"] == 2), None)
    if page_2_fields:
        out = draw_field_boxes(pdf_path, 2, page_2_fields, out_path="field_boxes_page2.png")
        print(f"saved: {out}")