# -*- coding: utf-8 -*-
"""sample_chatbox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nk2P9b13gYTzifnSr64V1zmqXIvkUo-x
"""

!pip install -q llama-index-llms-google-genai llama-index

import os
GOOGLE_API_KEY="API-KEY-HIDDEN"
os.environ["GOOGLE_API_KEY"]=GOOGLE_API_KEY

from llama_index.llms.google_genai import GoogleGenAI
from llama_index.core.llms import ChatMessage
!pip install -q nest_asyncio
import nest_asyncio
nest_asyncio.apply()
llm=GoogleGenAI(model="gemini-3.5-flash",
                )

def simple_chatbot():
  print(" Simple chatbot")
  print("You can type 'exit' to end the conversation")
  print("-"*50)

  messages=[]
  while True:
    user_input=input("\n you:")

    if user_input.lower() in ["exit","quit","bye"]:
      print("\n Goodbye: It was nice chatting with you. BBYYEE")
      break
    messages.append(ChatMessage(role="user", content=user_input))
    try:
      response=llm.chat(messages)
      print(f"\n chatBot said: {response.message.content}")
      messages.append(ChatMessage(role="assistant",content=response.message.content))
    except Exception as e:
      print("There was an error")
      print(e)
if __name__=="__main__":
  simple_chatbot()