# -*- coding: utf-8 -*-
"""Tesseract_Paddle_Easy_Ocr_base_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_s6rZ1f4Yqqxjvz0JstPQXoCO87CbwnL
"""

import sys, platform, subprocess
print("Python  :", sys.version.split()[0])
print("Platform:", platform.platform())

try:
    print(subprocess.check_output(
        ["nvidia-smi", "--query-gpu=name,memory.total,driver_version",
         "--format=csv,noheader"], text=True).strip())
except Exception:
    print("GPU     : none — CPU runtime")

try:
    print(subprocess.check_output(["nvcc", "--version"], text=True).strip().splitlines()[-1])
except Exception:
    print("nvcc    : not found")

!apt-get -qq update

!apt-get -qq install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev\poppler-utils libgl1 libglib2.0.0
!tesseract --version

!apt-get -qq install -y libtesseract-dev poppler-utils

!pip install -q\
pytesseract\
easyocr\
pdf2image pymupdf\
opencv-python-headless\
pillow pandas
!pip install -q  paddleocr
!pip install -q paddlepaddle==3.2.2

import numpy, cv2, torch, paddle, easyocr, paddleocr, pytesseract
print("numpy", numpy.__version__)
print("torch", torch.__version__)
print("paddle", paddle.__version__)
print("easyocr", easyocr.__version__)
print("paddleocr", paddleocr.__version__)
print("all imports OK")

from google.colab import files
uploaded=files.upload()
DOC_PATH=list(uploaded.keys())[0]
print("Uploaded:",DOC_PATH)

import fitz
DPI=300
def load_pages(path,dpi=DPI):
  doc=fitz.open(path)
  pages=[]
  for page in doc:
    pix=page.get_pixmap(dpi=dpi)
    pages.append(pix)
  return pages
pages=load_pages(DOC_PATH)
print(f"{len(pages)} page(s) at {DPI} DPI")
print(f"First page: {pages[0].width} x {pages[0].height} px")
print(repr(fitz.open(DOC_PATH)[0].get_text()[:200]))

import numpy as np
def pixmap_to_array(pix):
  img=np.frombuffer(pix.samples,dtype=np.uint8).reshape(pix.height,pix.width,pix.n)
  return img[:,:,:3]

currPage=pixmap_to_array(pages[0])
baselineData=fitz.open(DOC_PATH)[0].get_text()

import pytesseract
from pytesseract import Output
result=pytesseract.image_to_data(currPage,lang="eng",output_type=Output.DICT)
words=[]
for i in range(len(result["text"])):
  text=result["text"][i].strip()
  conf=result["conf"][i]

  if text and conf != -1:
    words.append({"text":text,"conf":conf,"left":result["left"][i],"top":result["top"][i], "width": result["width"][i],
            "height": result["height"][i],})
for word in words:
  print("")
  print(word)

from paddleocr import PaddleOCR

paddle_engine = PaddleOCR(
    lang="en",
    device="cpu",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

paddle_raw = paddle_engine.predict(currPage)
for res in paddle_raw:
    p_texts = res["rec_texts"]
    p_scores = res["rec_scores"]
    p_polys = res["rec_polys"]

print(len(p_texts), "detections")

def paddleocr_to_words(texts, scores, polys):
    words = []
    for text, score, poly in zip(texts, scores, polys):
        xs = [p[0] for p in poly]
        ys = [p[1] for p in poly]
        words.append({
            "text": text,
            "conf": score,
            "left": min(xs),
            "top": min(ys),
            "width": max(xs) - min(xs),
            "height": max(ys) - min(ys),
        })
    return words

paddle_words = paddleocr_to_words(p_texts, p_scores, p_polys)

paddle_document_text = "\n".join(reconstruct_lines(paddle_words))
print(paddle_document_text)



def reconstruct_lines(words):
    if not words:
        return []
    heights = [w["height"] for w in words]
    row_tolerance = max(10, int(sorted(heights)[len(heights)//2] * 0.6))

    words_sorted = sorted(words, key=lambda w: w["top"])
    lines = []
    current_line = [words_sorted[0]]
    for w in words_sorted[1:]:
        if abs(w["top"] - current_line[-1]["top"]) <= row_tolerance:
            current_line.append(w)
        else:
            lines.append(current_line)
            current_line = [w]
    lines.append(current_line)

    readable_lines = []
    for line in lines:
        line_sorted = sorted(line, key=lambda w: w["left"])
        readable_lines.append(" ".join(w["text"] for w in line_sorted))
    return readable_lines

import json
def to_native(v):
    return v.item() if hasattr(v, "item") else v

clean_words = [{k: to_native(v) for k, v in w.items()} for w in paddle_words]

with open("paddle_output.json", "w") as f:
    json.dump(clean_words, f, indent=2)

print(json.dumps(clean_words, indent=2))

import easyocr
reader=easyocr.Reader(["en"],gpu=False)
easy_out=reader.readtext(currPage)

def easyocr_to_words(raw):
  words=[]
  for box,text,conf in raw:
    xs=[p[0] for p in box]
    ys = [p[1] for p in box]
    words.append({
        "text": text,
        "conf": conf,
        "left": min(xs),
        "top": min(ys),
        "width": max(xs) - min(xs),
        "height": max(ys) - min(ys),
        })
  return words
easy_words = easyocr_to_words(easy_out)

clean_easy_words = [{k: to_native(v) for k, v in w.items()} for w in easy_words]

with open("easyocr_output.json", "w") as f:
    json.dump(clean_easy_words, f, indent=2)

print(json.dumps(clean_easy_words, indent=2))

print(len(clean_easy_words), "entries")